apiVersion: v1
kind: Service
metadata:
  name: todo-list-service
spec:
  selector:
    app: todo-list
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort  # ClusterIP ou NodePort ou LoadBalancer  Use NodePort para acesso externo em um ambiente de desenvolvimento
